/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, IOException {
        //TestCases tests = new TestCases(); // Initialize your test class


        //TODO: call your test case functions one after other here
//        AmazonSearch search = new AmazonSearch();
//        search.testCase01();
//        search.endTest();
        //==============================================================

//        CountOfHyperLinks hyperLinks = new CountOfHyperLinks();
//        hyperLinks.testCase02();
//        hyperLinks.endTest();
        //===============================================================

//        LinkedInPost linkedIn = new LinkedInPost();
//        linkedIn.testCase03();
//        linkedIn.endTest();

        //=================================================================
//        BookMyShowImgUrl bms = new BookMyShowImgUrl();
//        bms.testCase04();
//        bms.endTest();
        //=================================================================

//        NestedFrames frames = new NestedFrames();
//        frames.testCase05();
//        frames.endTest();

        //===================================================================

//        IMDB imdb = new IMDB();
//        imdb.testCase06();

        //===================================================================
//        WindowHandling windHan = new WindowHandling();
//        windHan.testCase07();

        //==================================================================

        LinkedInImgPost linkedInPost = new LinkedInImgPost();
        linkedInPost.testCase09();


        //tests.testCase01();

        //END Tests


        //tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
